### ISSUE TITLE
How to test the smart rotate on the smart stack?

### ISSUE THREAD

**Issue by cafedeichi** [wojciech-kulik/WidgetKit-Demo#1]
Hello,

Thanks a lot for a nice WidgetKit sample project. It's very easy to understand how to implement a widget and its configuration. While I recently have been looking for how to test Smart Rotate, I found your sample code. It supports INInteraction donation, however, the widget has never appeared on a Smart Stack in iOS 14.7.1 with Xcode 12.5.1, notwithstanding donating interactions so mush from the app. Since I can see the Siri Suggestion on Spotlight Search, I think the donation work fine properly.

As far as I see Developer forums, it seems like some developers have the same issue as mine. (I am also going to try to support Widget Suggestions by the way.)
https://developer.apple.com/forums/thread/686136

I really appreciate if you could let me know the solution or some tips regarding the Smart Rotate debugging.

Regards,

**Comment by wojciech-kulik** [comment]
Hi, I think I asked some time ago a question on Apple's forum about testing donation and they said there is no way to do that. The only thing you can do (I think) is to check out logs - there appears some information about donations.

You can also try to simulate smart stack rotations. Just make two widgets, stack them and simulate returning different TimelineEntryRelevance, remember it might not be instant.
https://developer.apple.com/documentation/widgetkit/timelineentryrelevance

**Comment by cafedeichi** [comment]
@wojciech-kulik 
Hi, After asked you the question, I found it easier to use INRelevantShortcut to let the system suggest my widgets. It worked fine anyway. I'll try to implement TimelineEntryRelevance as well. Thanks a lot for your advice!!
